## Parsing PDFs with Tables

I've been battling PDFs with tables for at least 10 years (you can read about it in my [first O'Reilly book]()) but don't bother because it's gotten much easier!

You can learn more about [Docling](https://www.docling.ai/) workflows via their documentation.

Some other libraries to check out:

- [pypdf](https://pypi.org/project/pypdf/): Have a simple PDF and just need text, use this!
- [SpaCy Layout](https://github.com/explosion/spacy-layout): Use NLP tools directly in the library you use to extact!

In [2]:
from docling.datamodel.base_models import InputFormat
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling.datamodel.pipeline_options import PdfPipelineOptions, TableFormerMode
import pandas as pd

In [3]:
# Configure pipeline options for best table extraction quality
pipeline_options = PdfPipelineOptions(do_table_structure=True)
pipeline_options.table_structure_options.do_cell_matching = False  # Avoids merging rows/columns
pipeline_options.table_structure_options.mode = TableFormerMode.ACCURATE  # Most accurate model

In [4]:
# Create the document converter with these options
doc_converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
    }
)

In [6]:
ls ../data

gebietseigene_pflanzen.pdf

In [7]:
conv_res = doc_converter.convert('../data/gebietseigene_pflanzen.pdf', page_range=(47, 52))

In [8]:
df_list = []
for i, table in enumerate(conv_res.document.tables):
    df = table.export_to_dataframe(doc=conv_res.document)
    df_list.append(df)

In [9]:
len(df_list)

4

In [10]:
[len(d.columns) for d in df_list]

[13, 13, 14, 13]

In [11]:
df_list[2]

,T abelle 11: L iste zur A uswahl gebietseigener krautiger P.W issenschaftlicher N ame,T abelle 11: L iste zur A uswahl gebietseigener krautiger P.D eutscher N ame,flanzen fü r B erlin (F ortsetzung) B iotoptypen.en nras e Trock,flanzen fü r B erlin (F ortsetzung) B iotoptypen.r rasflu erg Silb,flanzen fü r B erlin (F ortsetzung) B iotoptypen.icher re en basen nras rte e do Trock Stan,flanzen fü r B erlin (F ortsetzung) B iotoptypen.ige hrjähr en bis me lflur era Zwei- Rud,flanzen fü r B erlin (F ortsetzung) B iotoptypen.rasen Zier re Mage,flanzen fü r B erlin (F ortsetzung) B iotoptypen.wiesen ch Fris,"flanzen fü r B erlin (F ortsetzung) B iotoptypen.Wechselfeuch- len) = Rigo en (WF h für wies , auc ht ger Feuc tezei",flanzen fü r B erlin (F ortsetzung) B iotoptypen.ieder genr d Seg te un rich Röh,flanzen fü r B erlin (F ortsetzung) B iotoptypen.nzen fla erp Wass,flanzen fü r B erlin (F ortsetzung) B iotoptypen.nzen fla erp Wass,flanzen fü r B erlin (F ortsetzung) B iotoptypen. hölzen e ume an G nsä de Stau,flanzen fü r B erlin (F ortsetzung) B iotoptypen.er rtig walda chicht de uts n Kra Bestä
0,Leucanthemum ircutianum,Fettwiesen-Margerite,(x),,,x,,,,,,,,
1,Linaria vulgaris,Gemeines Leinkraut,,,,x,,,,,,,,
2,Lotus corniculatus,Gemeiner Hornklee,(x),,,,x,x,,,,,,
3,Lotus pedunculatus,Sumpf-Hornklee,,,,,,,x,,,,,
4,Luzula campestris,Gemeine Hainsimse,x,,,,x,(x),,,,,,
5,Luzula multiflora,Vielblütige Hainsimse,,,,,,,,,,,,x
6,Luzula pilosa,Haar-Hainsimse,,,,,,,,,,,,x
7,Lycopus europaeus,Ufer-Wolfstrapp,,,,,,,,x,,,,
8,Lysimachia nummularia,Pfennigkraut,,,,,,(x),(WF),x,,,,
9,Lysimachia vulgaris,Gemeiner Gilbweiderich,,,,,,,(WF),x,,,,
10,Lythrum salicaria,Gemeiner Blutweiderich,,,,,,,WF,(x),,,,
11,Malva alcea,Siegmarswurz,,,,x,,x,,,,,,
12,Malva sylvestris sylvestris ssp.,"Wilde Malve, Rosspappel",,,,x,,,,,,,,
13,Mentha aquatica,Wasser-Minze,,,,,,,(x),x,,,,
14,Milium effusum,Wald-Flattergras,,,,,,,,,,,,x
15,Molinia caerulea,Pfeifengras,,,,,,,x,,,,,
16,Mycelis muralis,Mauerlattich,,,,(x),,,,,,,,x
17,,Große Mummel,,,,,,,,,,x,,
18,Nymphaea alba,Weiße Seerose,,,,,,,,,x,x,,
19,Ononis repens ssp.,Kriechende Hauhechel,,,x,(x),,,,,,,,
20,procurrens,Kriechende Hauhechel,(x),,x,(x),x,,,,,,,
21,GLYPH(cmap:df00)apaver rhoeas,Klatsch-Mohn,,,,x,,,,,,,,
22,GLYPH(cmap:df00)astinaca sativa s.l.,Pastinak,,,,x,,,,,,,x,
23,GLYPH(cmap:df00)ersicaria amphibia,Wasser-Knöterich,,,,,,,,,,x,,
24,GLYPH(cmap:df00)hleum phleoides,Steppen-Lieschgras,,,x,,,,,,,,,
25,GLYPH(cmap:df00)hragmites australis,Gemeines Schilf,,,,,,,,x,,,,
26,GLYPH(cmap:df00)impinella major,Große Pimpinelle,,,,,,x,,,,,,
27,GLYPH(cmap:df00)lantago lanceolata,Spitz-Wegerich,(x),,,,(x),x,,,,,,
28,GLYPH(cmap:df00)lantago media,Mittel-Wegerich,,,(x),,x,(x),,,,,,
29,GLYPH(cmap:df00)oa angustifolia,Schmalblättriges Rispengras,x,,,x,(x),,,,,,,
30,GLYPH(cmap:df00)oa nemoralis,Hain-Rispengras,,,,,x,,,,,,,x
31,GLYPH(cmap:df00)oa pratensis,Wiesen-Rispengras,,,,,x,x,,,,,,
32,GLYPH(cmap:df00)oa trivialis,Gemeines Rispengras,,,,,,x,x,,,,,
33,GLYPH(cmap:df00)olygonatum multiflorum,Vielblütige Weißwurz,,,,,,,,,,,,
34,GLYPH(cmap:df00)otamogeton crispus,Krauses Laichkraut,,,,,,,,,,x,,
35,GLYPH(cmap:df00)otentilla argentea s.l.,Silber-Fingerkraut,x,,,,(x),,,,,,,
36,GLYPH(cmap:df00)otentilla incana,Sand-Fingerkraut,,,x,,,,,,,,,
37,GLYPH(cmap:df00)otentilla incana,Sand-Fingerkraut,,,x,,,,,,,,,
38,GLYPH(cmap:df00)otentilla reptans,Kriechendes Fingerkraut,,,,,x,,,,,,,
39,GLYPH(cmap:df00)runella vulgaris,Gemeine Braunelle,x,,,,,,,,,,,
40,Ranunculus acris ssp. acris,Scharfer Hahnenfuß,,,,,x,(x),(x),,,,,
41,Ranunculus acris ssp.,Scharfer Hahnenfuß,,,,,,x,(x),,,,,
42,Ranunculus acris ssp. acris,Scharfer Hahnenfuß Gewöhnliches Scharbocks-,,,,,,,,,,,,x
43,Ranunculus repens,Kriechender Hahnenfuß,,,,,x,x,(WF),,,,,

In [12]:
df_list[3]

,T abelle 11: L iste zur A uswahl gebietseigener krautiger P A rten.A rten,T abelle 11: L iste zur A uswahl gebietseigener krautiger P A rten.,flanzen fü r B erlin (F ortsetzung).en nras e Trock,flanzen fü r B erlin (F ortsetzung).r rasflu erg Silb,flanzen fü r B erlin (F ortsetzung).icher re en basen nras rte e do Trock Stan,flanzen fü r B erlin (F ortsetzung).ige hrjähr en bis me lflur era Zwei- Rud,flanzen fü r B erlin (F ortsetzung).rasen Zier re Mage,flanzen fü r B erlin (F ortsetzung).iesen chw Fris x,"flanzen fü r B erlin (F ortsetzung).Wechselfeuch- len) = Rigo en (WF h für wies , auc ht ger Feuc tezei",flanzen fü r B erlin (F ortsetzung).ieder genr d Seg te un rich Röh,flanzen fü r B erlin (F ortsetzung).nzen fla erp Wass,flanzen fü r B erlin (F ortsetzung). hölzen e ume an G nsä de Stau,flanzen fü r B erlin (F ortsetzung).er rtig walda hicht de utsc än Kra Best
0,Rumex acetosa,Wiesen-Sauerampfer,,,,,,x,(x),,,,
1,Rumex hydrolapathum,"Hoher Ampfer, Fluss-Ampfer",,,,,,,,x,,,
2,Salvia pratensis,Wiesen-Salbei,,,x,,,(x),,,,,
3,Saponaria officinalis,Echtes Seifenkraut,,,,x,,,,,,,
4,Saxifraga granulata,Körnchen-Steinbrech,(x),,,,x,,,,,,
5,Schoenoplectus lacustris,Gemeine Teichsimse,(x),,,,,(x),,x,,,
6,Scrophularia nodosa,Gemeine Teichsimse,,,,,,,,,,,x
7,Scutellaria galericulata,Gemeines Helmkraut,,,,,,,,x,,,
8,Securigera varia,Bunte Kronwicke,,,(x),,,x,,,,x,
9,Sedum acre,Scharfer Mauerpfeffer,,,(x),,,x,,,,x,
10,Sedum maximum,Scharfer Mauerpfeffer,x,x,,,(x),,,,,,
11,Sedum maximum,Große Fetthenne,(x),,,,,,,,,x,
12,Sedum sexangulare,Milder Mauerpfeffer,x,,,,(x),,WF,,,,
13,Silene flos-cuculi,Kuckucks-Lichtnelke,,,,,,(x),WF,,,,
14,Silene vulgaris ssp. vulgaris,Gewöhnliches Leimkraut,(x),,,x,,,,,,(x),
15,Sium latifolium,Breitblättriger Merk,,,,,,,,,,,
16,Sparganium erectum erectum ssp.,Ästiger Igelkolben,,,,,,,,x,,,
17,Stachys palustris,Sumpf-Ziest,,,,,,,WF,,,,
18,Stellaria graminea,Gras-Sternmiere,,,,,,x,(x),,,,
19,Stellaria holostea,Echte Sternmiere,,,,,,,,,,,x
20,Symphytum officinale,Gemeiner Beinwell,,,,,,,x,,,,
21,Teesdalia nudicaulis Thalictrum flavum,Bauernsenf,(x),x,,,,,,,,,
22,Thalictrum flavum,Gelbe Wiesenraute,,,,,,,WF,,,,
23,Thymus pulegioides pulegioides ssp.,Gemeiner Thymian,(x),,x,,(x),,,,,,
24,Thymus serpyllum,Sand-Thymian,x,,x,,(x),,,,,,
25,Tragopogon pratensis pratensis ssp.,Wiesen-Bocksbart,,,,,,x,,,,x,
26,Trifolium arvense,Hasen-Klee,x,x,,,,,,,,,
27,Trifolium pratense,"Zickzack-Klee, Mittel-Klee",x,x,,,,,,,,,
28,Trifolium medium,"Zickzack-Klee, Mittel-Klee",,,,,,,,,,x,
29,Typha angustifolia,Rot-Klee,,,,,,x,,,,,
30,Valeriana officinalis,Echter Baldrian,,,,,,,WF,x,,,
31,Verbascum densiflorum,Großblütige Königskerze,,,,x,,,,,,(x),
32,Verbascum lychnitis,Großblütige Königskerze,,,,x,,,,,,(x),
33,Verbascum lychnitis,Mehlige Königskerze,,,,(x),,,,,,x,
34,Verbascum phlomoides,Windblumen-Königskerze,,,,(x),,,,,,x,
35,Verbascum phlomoides,Windblumen-Königskerze,,,,(x),,,,,,x,
36,Veronica chamaedrys,Gamander-Ehrenpreis,,,,,x,(x),,,,x,
37,Veronica chamaedrys,Gamander-Ehrenpreis,,,,,x,(x),,,,,
38,Vicia angustifolia angustifolia ssp.,Schmalblättrige Wicke,x,,,,(x),x,,,,,
39,Vicia angustifolia angustifolia ssp.,,x,,,(x),,x,,,,,
40,Vicia cracca Vicia lathyroides,Vogel-Wicke,,,,(x),,x,,,,,
41,Vicia lathyroides,Platterbsen-Wicke,(x),x,,,,,,,,,
42,Vicia lathyroides,Hain-Veilchen,,,,,,,,,,,x
43,Viola riviniana,Hain-Veilchen,,,,,,,,,,x,x
44,Viola riviniana,Hain-Veilchen,,,,,,,,,,x,x

In [13]:
broken_df = df_list.pop(2)

In [14]:
columns = [
    'Wissenschaftlicher Name', 
    'Deutscher Name', 
    'Trockenrasen', 
    'Silbergrasflur',
    'Trockenrasen basenreicher Standorte',
    'Zwei- bis mehrjährige Ruderalfluren',
    'Magere Zierrasen',
    'Frischwiesen',
    'Feuchtwiesen',
    'Röhrichte und Seggenrieder',
    'Wasserpflanzen',
    'Staudensäume an Gehölzen',
    'Krautschicht waldartiger Bestände',
]

In [15]:
for d in df_list:
    d.columns = columns

In [16]:
merged_df = pd.concat(df_list, ignore_index=True)

In [17]:
merged_df

,Wissenschaftlicher Name,Deutscher Name,Trockenrasen,Silbergrasflur,Trockenrasen basenreicher Standorte,Zwei- bis mehrjährige Ruderalfluren,Magere Zierrasen,Frischwiesen,Feuchtwiesen,Röhrichte und Seggenrieder,Wasserpflanzen,Staudensäume an Gehölzen,Krautschicht waldartiger Bestände
0,W issenschaftlicher N ame,D eutscher N ame,en nras e Trock,r rasflu erg Silb,icher re en basen nras rte e do Trock Stan,hrjähr en bis me lflur i- era Zwe Ru...,rrasen Zie re Mage,iesen chw Fris,Wechselfeuch- len) = Rigo en (WF ch ...,genr d Seg te un rich Röh,nzen fla erp Wass,hölzen e ume an G nsä de Stau,er rtig walda hicht de utsc n Kra Bestä
1,Achillea millefolium s.str.,Sumpf-Schafgarbe,,,,(x),(x),x,,,,(x),
2,Achillea ptarmica,Sumpf-Schafgarbe,,,,,,,x,,,,
3,Agrimonia eupatoria,Kleiner Odermennig,(x),,(x),,,,,,,x,
4,Agrostis capillaris,,x,,,,(x),(x),,x,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,Vicia cracca Vicia lathyroides,Vogel-Wicke,,,,(x),,x,,,,,
130,Vicia lathyroides,Platterbsen-Wicke,(x),x,,,,,,,,,
131,Vicia lathyroides,Hain-Veilchen,,,,,,,,,,,x
132,Viola riviniana,Hain-Veilchen,,,,,,,,,,x,x
133,Viola riviniana,Hain-Veilchen,,,,,,,,,,x,x

In [18]:
merged_df[merged_df['Frischwiesen'].str.contains('x')]

,Wissenschaftlicher Name,Deutscher Name,Trockenrasen,Silbergrasflur,Trockenrasen basenreicher Standorte,Zwei- bis mehrjährige Ruderalfluren,Magere Zierrasen,Frischwiesen,Feuchtwiesen,Röhrichte und Seggenrieder,Wasserpflanzen,Staudensäume an Gehölzen,Krautschicht waldartiger Bestände
1,Achillea millefolium s.str.,Sumpf-Schafgarbe,,,,(x),(x),x,,,,(x),
4,Agrostis capillaris,,x,,,,(x),(x),,x,,,
7,Alopecurus pratensis,Wiesen-Fuchsschwanz,,,,,,(x),x,,,,
11,Anthoxanthum odoratum,Gemeines Ruchgras,(x),,,,x,x,,,,(x),
12,Anthriscus sylvestris,Wiesen-Kerbel,,,,,,x,,,,,
13,Armeria maritima elongata ssp.,Gemeine Grasnelke,x,,,,(x),(x),,,,,
23,Campanula rotundifolia,Rundblättrige Glockenblume,,,,,,x,,,,x,
24,Campanula rotundifolia,Rundblättrige Glockenblume,,,,,,x,,,,,
31,Carex praecox ssp. praecox,Frühe Segge,(x),,,,x,x,,,,,
32,Carex pseudocyperus,Scheinzyper-Segge,,,,,,x,,x,,,
33,Centaurea jacea,Wiesen-Flockenblume,,,,(x),,x,,,,,
43,Corynephorus,Wiesen-Pippau,,,,,,x,,,,,
47,Dactylis glomerata,Gemeines Knäuelgras,,,,,(x),x,,,,,
48,Daucus carota,Wilde Möhre,,,,x,,x,,,,x,
59,Falcaria vulgaris,Sichelmöhre,,,,x,,(x),,,,,
62,Festuca pratensis,Wiesen-Schwingel,,,,,(x),x,,,,,
63,Festuca rubra ssp. rubra,Rot-Schwingel,,,,,x,(x),(x),,,,
67,Galium album,Weißes Labkraut,,,,,,x,,,,,x
69,Galium verum ssp. verum,Echtes Labkraut,(x),,x,,(x),x,,,,,
76,Helictotrichon pubescens,Flaumhafer,,,,,,x,,,,,
77,Heracleum sphondylium ssp. sphondylium,Wiesen-Bärenklau,,,,,,(x),(x),,,,
85,Lathyrus pratensis,Wiesen-Platterbse,,,,,,x,(x),,,,
87,Leontodon hispidus ssp. hispidus,Rauher Löwenzahn,,,x,,,(x),,,,,
88,ssp. hispidus,Rauher Löwenzahn,,,x,,,(x),,,,,
89,Rumex acetosa,Wiesen-Sauerampfer,,,,,,x,(x),,,,
91,Salvia pratensis,Wiesen-Salbei,,,x,,,(x),,,,,
94,Schoenoplectus lacustris,Gemeine Teichsimse,(x),,,,,(x),,x,,,
97,Securigera varia,Bunte Kronwicke,,,(x),,,x,,,,x,
98,Sedum acre,Scharfer Mauerpfeffer,,,(x),,,x,,,,x,
102,Silene flos-cuculi,Kuckucks-Lichtnelke,,,,,,(x),WF,,,,
107,Stellaria graminea,Gras-Sternmiere,,,,,,x,(x),,,,
114,Tragopogon pratensis pratensis ssp.,Wiesen-Bocksbart,,,,,,x,,,,x,
118,Typha angustifolia,Rot-Klee,,,,,,x,,,,,
125,Veronica chamaedrys,Gamander-Ehrenpreis,,,,,x,(x),,,,x,
126,Veronica chamaedrys,Gamander-Ehrenpreis,,,,,x,(x),,,,,
127,Vicia angustifolia angustifolia ssp.,Schmalblättrige Wicke,x,,,,(x),x,,,,,
128,Vicia angustifolia angustifolia ssp.,,x,,,(x),,x,,,,,
129,Vicia cracca Vicia lathyroides,Vogel-Wicke,,,,(x),,x,,,,,